import { z } from 'zod';
import { translatable } from './translatable';
import { species } from './species';
import { move } from './move';
import { item } from './item';
import { journey } from './journey';

/**
 * The top-level game world — the compiled output of the content pipeline.
 * Authors do NOT edit this file directly; it's the sum of every spine
 * file after Zod validation + Tatoeba resolution.
 *
 * The new architecture (post region-schema removal) treats Tiled `.tmx` files
 * under `public/assets/maps/<map_id>.tmj` as the per-region authoring format
 * — no per-region JSON exists in spine. The arc through those maps is
 * declared in `src/content/spine/journey.json`; the L4 interaction layer
 * reads `journey` here to drive scene loading and progression.
 */
export const world = z.object({
  schema_version: z.literal(1),
  title: translatable,
  /** The first beat's `map_id` is implicitly the start region — readers can
   *  derive it as `world.journey.beats[0].map_id`. This explicit field is
   *  retained for save-file backwards compatibility and the dev harness. */
  start_region_id: z.string(),
  species: z.array(species).min(1),
  moves: z.array(move).min(1),
  items: z.array(item).default([]),
  /** The authored arc — see `src/content/spine/journey.json` and
   *  `docs/JOURNEY.md`. Source of truth for the L4 interaction layer. */
  journey,
});
export type World = z.infer<typeof world>;
