import { z } from 'zod';
import { translatable } from './translatable';
import { species } from './species';
import { move } from './move';
import { item } from './item';
import { region } from './region';

/**
 * The top-level game world — the compiled output of the content pipeline.
 * Authors do NOT edit this file directly; it's the sum of every spine
 * file after Zod validation + Tatoeba resolution.
 *
 * `start_region_id` is where a fresh save drops the player. Region-to-
 * region travel is driven by `warps` inside each region.
 */
export const world = z.object({
  schema_version: z.literal(1),
  title: translatable,
  start_region_id: z.string(),
  species: z.array(species).min(1),
  moves: z.array(move).min(1),
  items: z.array(item).default([]),
  regions: z.array(region).min(1),
  /** Main quest spine — human-readable beat names that the engine uses
   *  as flag keys. Ordered. */
  main_spine: z.array(
    z.object({
      id: z.string(),
      summary: z.string(),
    }),
  ),
});
export type World = z.infer<typeof world>;
